name: Build OpenWrt-X60Pro

on:
  workflow_dispatch:
    inputs:
      TARGET:
        description: 编译机型
        default: ruijie_rg-x60-pro
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 拉取源码
        uses: actions/checkout@main
        with:
          repository: Eric-wang58/MT798X-6.6-24.10
          ref: openwrt-24.10-6.6
          depth: 1

      - name: 安装编译依赖
        run: |
          sudo apt update && sudo apt install -y build-essential libncurses-dev gawk flex bison git python3 python3-pip unzip wget curl rsync

      - name: 更新FEEDS
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 导入X60Pro默认配置
        run: cp defconfig/mt7986-ax6000.config .config

      - name: 一键开启所需插件
        run: |
          # DDNS
          sed -i 's/# CONFIG_PACKAGE_luci-app-ddns is not set/CONFIG_PACKAGE_luci-app-ddns=y/' .config
          sed -i 's/# CONFIG_PACKAGE_ddns-scripts is not set/CONFIG_PACKAGE_ddns-scripts=y/' .config
          # OpenClash
          sed -i 's/# CONFIG_PACKAGE_luci-app-openclash is not set/CONFIG_PACKAGE_luci-app-openclash=y/' .config
          sed -i 's/# CONFIG_PACKAGE_openclash is not set/CONFIG_PACKAGE_openclash=y/' .config
          # AdGuardHome
          sed -i 's/# CONFIG_PACKAGE_luci-app-adguardhome is not set/CONFIG_PACKAGE_luci-app-adguardhome=y/' .config
          sed -i 's/# CONFIG_PACKAGE_adguardhome is not set/CONFIG_PACKAGE_adguardhome=y/' .config
          # Passwall
          sed -i 's/# CONFIG_PACKAGE_luci-app-passwall is not set/CONFIG_PACKAGE_luci-app-passwall=y/' .config
          sed -i 's/# CONFIG_PACKAGE_passwall is not set/CONFIG_PACKAGE_passwall=y/' .config
          sed -i 's/# CONFIG_PACKAGE_passwall2 is not set/CONFIG_PACKAGE_passwall2=y/' .config
          make defconfig

      - name: 开始编译
        run: make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt-X60Pro固件
          path: bin/targets/mediatek/filogic/
